version: "3.9"
services:
  api:
    build:
      # The directory of which a target dockerfile exists
      context: ./api
      dockerfile: Dockerfile.dev # Docker Compose finds Dockerfile by
                                        # default. If you had other Dockerfiles,
                                        # this is how you'd specify them.
    ports:
      - "8080:8080"
      - "4000:4000"
    volumes:
       - ./api:/api
    env_file: .env
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogger
