version: "3.9"
services:
  api:
    image: localhost:5001/company/api:${TAG}
    ports:
      - "8888:8080"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogger
